### ISSUE TITLE
Saving keywords in GUI removes all keywords from filter

### ISSUE THREAD

**Issue by fhemberger** [hiway/mastodon-filter#2]
1. Launch GUI
2. Select filter with existing keywords
3. Copy & paste additional keywords from a different filter (with the intent to move them to this filter)
4. Click "Save" (Console output: "Saving filter X with Y keywords.")
5. Keyword list for this filter is now empty (also on the Mastodon web interface)

**Comment by hiway** [comment]
Let me try and reproduce this, thank you.

**Comment by hiway** [comment]
@fhemberger Sorry for the lost keywords! 

I found an issue where added and deleted keywords were clobbering index for parameters sent to server. 

Commit [54c75ec](https://github.com/hiway/mastodon-filter/commit/54c75ec985dd7a7def5e734cb708efd17aaec501) should fix the issue you faced.

Could you please pull latest changes and confirm?

Edit: If you used the Mac app, I've also released a new version, could try that instead.

**Comment by fhemberger** [comment]
Hmm, okay, it doesn't delete *all* keywords from a filter anymore, just the hashtags.

**Comment by hiway** [comment]
Ah, I haven't been adding "#" before words as Mastodon filters hashtags as well, but I see the use case for it.

Will work on supporting that.

Thank you for your time and feedback!

**Comment by hiway** [comment]
Ha! I had a line ignoring keywords starting with "#"  as I initially started with using text files and lines starting with "#" are considered comments by convention.

Fixed it!
